### ISSUE TITLE
我下载后 npm run dev:client 代码有错误

### ISSUE THREAD

**Issue by PN-linshifeng** [fridaydream/react-cnode-ssr#1]
发现有两处错误  怎么处理呢
1：Warning: Material-UI: you are using the deprecated typography variants that will be removed in the next major release.
Please read the migration guide under https://material-ui.com/style/typography#migration-to-typography-v2

2：Uncaught TypeError: Cannot read property 'user' of undefined
    at AppState.ini

**Comment by fridaydream** [comment]
第一个问题是 警告啊，typography这个api 要被下一个版本移除，第二个问题是要 npm run dev:server开启后台node服务

**Comment by fridaydream** [comment]
@PN-linshifeng   

init(user = {}) {
    if (user.user) {
      this.user = user
    }
  }
1.这个地方，需要个判断一下，我改了，提交了代码，之前我测试的时候都是走的session没问题，如果node里面session没了，确实会出现这个问题，user这个就不是对象了，是undefined,所以会报错。

2.这个警告在生产环境不会报的。

**Comment by fridaydream** [comment]
已修改，提交，感谢issue
