### ISSUE TITLE
大佬请问遇到过这种情况吗？卡在这里了 T_T

### ISSUE THREAD

**Issue by neigthdi** [fridaydream/react-cnode-ssr#2]
请问一下，测试环境的时候，我在list页面
------------
bootstrap这个函数不请求fetchTopics这个函数的时候，在客户端和服务端都能正常显示页面，但是服务端里面的topics这个变量里面是空的，右键的检查网页源代码，请求的那些数据也没有，只有material和topci页面写死的那些（正确的应该有列表数据）。
------------
bootstrap这个函数请求了fetchTopics这个函数的时候，客户端正常显示，但是服务端只显示“{}”这个符号，NetWork的index也是500错误。（toJson这个函数是有写的）。
bootstrap里面的then函数可以打印到获取的数据，但是await bootstrapper(app)后面的console就不能打印出来，卡死在那里
服务端打印错误是如下
--------------------------------------------
Warning: Rendering <Context.Consumer.Provider> is not supported and will be removed in a future major release. Did you mean to render <Context.Provider> instead?
Warning: Rendering <Context.Consumer.Consumer> is not supported and will be removed in a future major release. Did you mean to render <Context.Consumer> instead?
TypeError: Cannot read property 'dense' of undefined
    at Object.children (server-entry.js:33:81814)
    at recursive (C:\Users\Neigthdi\Desktop\react-ssr-no-nextjs-only-dev-pro-materialUi-demo-other\node_modules\react-tree-walker\dist\react-tree-walker.js:129:41)
    at C:\Users\Neigthdi\Desktop\react-ssr-no-nextjs-only-dev-pro-materialUi-demo-other\node_modules\react-tree-walker\dist\react-tree-walker.js:153:26
    at process._tickCallback (internal/process/next_tick.js:68:7)
--------------------------------------------
不明白dense是哪里的
另外，我是用express的  
请问大佬遇到过这个情况嘛？ 0_0

**Comment by neigthdi** [comment]
然后我down了你的例子，在电脑上运行8889和3333，3333没有列表数据以及样式，只有layout里面写死的（全部，分享，工作，问答这些也没有）。
topic里面的bootstrap函数没执行，就连打印console也没执行。
课程视频还没看完，卡在"dense"，只看到服务端渲染优化那里。
小白请教大佬_(:з」∠)_

**Comment by neigthdi** [comment]
找到原因了。是material-ui的原因。
升级之后，有几个会有冲突（ListItem，ListItemAvatar等几个的"dense"，在react-tree-walker会报错，undefined的）
_(:з」∠)_
日了狗了

**Comment by fridaydream** [comment]
package.json里面的 版本确实要固定版本，一些版本升级了，不兼容问题很多。

**Comment by fridaydream** [comment]
固定版本之后就好了，package.json部分包升级之后的不兼容问题。
